# Generated by Django 4.0.4 on 2022-05-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMedicineData',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_1mg', models.BigIntegerField(blank=True, db_column='ID_1MG', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('pack_size_label', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_discontinued', models.IntegerField(blank=True, null=True)),
                ('prescription_required', models.IntegerField(blank=True, null=True)),
                ('composition', models.CharField(blank=True, max_length=1000, null=True)),
                ('mrp_india', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_medicine_data',
            },
        ),
    ]
