# Generated by Django 4.0.4 on 2022-05-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('prescriptions', '0002_alter_prescriptions_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='medicines',
            field=models.ManyToManyField(db_constraint=False, to='medicines.rawmedicinedata'),
        ),
    ]
